all:
  children:
    front_hosts:
      hosts:
        swimtrack_front:
          ansible_host: proyecto_ia
          ansible_user: grupo1
          ansible_python_interpreter: /usr/bin/python3.12
          ansible_ssh_common_args: "-F {{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/config"
    gpu_hosts:
      hosts:
        swimtrack_gpu:
          ansible_host: proyecto_ia_gpu
          ansible_user: grupo1
          ansible_python_interpreter: /usr/bin/python3.12
          ansible_ssh_common_args: "-F {{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/config"
