swimtrack_front_revision: fe5a1b8991392afd0ee8a2da1bb867c55dd5a805
swimtrack_front_remote_user: grupo1
swimtrack_front_remote_home: /home/grupo1
swimtrack_front_repo_dir: /home/grupo1/swimtrack/swimtrack-front
swimtrack_front_repository: https://github.com/Benjjvv/swimtrack-front.git
swimtrack_front_url_prefix: /swimtrack/
swimtrack_front_port: 7101
swimtrack_front_vision_base_url: http://10.0.218.101:7001
swimtrack_front_require_vision_auth_token: true
swimtrack_front_verify_vision_api: true
