swimtrack_ai_revision: 4a4ae8942f39faddfbf5f2858e35fd7cf3015f39
swimtrack_ai_remote_user: grupo1
swimtrack_ai_remote_home: /home/grupo1
swimtrack_ai_repo_dir: /home/grupo1/swimtrack/swimtrack-ai
swimtrack_ai_network_mode: direct
swimtrack_ai_bind_host: 10.0.218.101
swimtrack_ai_port: 7001
